import type { ChartType } from '@/components/charts/BrandChart';

// Available database tables for chart generation
export const AVAILABLE_TABLES = [
  'SBI_Discussion_Topics',
  'SBI Average Scores',
  'SBI_Priorities_Age_Groups',
  'SBI Ranking Positions 2025 only',
  'SBI_Discussion_Topics_Geography',
  'SBI Ranking Scores 2011-2025',
  'age_groups',
  'SBI_Inflation_Stability_2025',
  'SBI_Knowledge',
  'SBI_purchasing_decision_industries',
  'materiality_areas__age_sbi',
  'materiality_areas_general_sbi',
  'SBI SBA 2011-2025',
  'SBI SBQ 2011-2025',
  'SBI_VHO_2021-2024',
  'SBI_behaviour_groups',
  'SBI_influences',
  'SB Ranking Scores 2019-2025 BY AGE',
] as const;

export type AvailableTable = typeof AVAILABLE_TABLES[number];

// Chart configuration generated by AI
export interface ChartConfiguration {
  chartType: ChartType;
  title: string;
  subtitle?: string;
  dataQuery: {
    table: AvailableTable;
    columns: string[];
    filters?: Record<string, string | number | boolean>;
    orderBy?: { column: string; ascending: boolean };
    limit?: number;
    groupBy?: string;
    aggregations?: {
      column: string;
      function: 'sum' | 'avg' | 'count' | 'min' | 'max';
      alias: string;
    }[];
  };
  xAxisField: string;
  yAxisField: string | string[];
  seriesField?: string;
  colorSequence?: 'primary' | 'sequential' | 'diverging' | 'categorical';
  options?: {
    showLegend?: boolean;
    showDataLabels?: boolean;
    stacked?: boolean;
    height?: number;
    xAxisTitle?: string;
    yAxisTitle?: string;
    tooltipFormat?: string;
  };
}

// User prompt for AI chart generation
export interface ChartPrompt {
  userMessage: string;
  context?: {
    selectedCountry?: string;
    selectedBrand?: string;
    selectedIndustry?: string;
    dateRange?: { start: string; end: string };
  };
}

// AI response with chart configuration
export interface ChartGeneratorResponse {
  success: boolean;
  configuration?: ChartConfiguration;
  explanation?: string;
  suggestedFollowups?: string[];
  error?: string;
}

// Conversation message
export interface ChartConversationMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  chartConfig?: ChartConfiguration;
}

// Chart Maker state
export interface ChartMakerState {
  messages: ChartConversationMessage[];
  currentChart: ChartConfiguration | null;
  isGenerating: boolean;
  error: string | null;
  generatedCharts: ChartConfiguration[];
}
